### ISSUE TITLE
Ajuda a gerar todos

### ISSUE THREAD

**Issue by AdolfoPD** [wagnerluis1982/sorte.py#2]
Tenho a seguinte duvida,, 

tenho um banco de dados assim, com mais de 14 milhões de linhas.

id | Jogo
1 | xx1x11xx1121x21
2 | x212x1121x111x1
3 | 211122x1x1211x1
4 | 21112x2121x11x1
5 | 2x22121x1121121
6 | 2211221x2x111x1
7 | 22111x2121x11x1

Quero saber quem quais são os "id | jogo" com 13 acertos comparado todos  4 milhões. 

Cada um dos jogos vai se submetido aos 4 milhões para dizer quantos jogos com 13 acertos têm e qual o id e o jogo.

**Comment by wagnerluis1982** [comment]
Olá, você não falou qual jogo, eu suponho que seja Lotofácil ou Lotomania, pela quantidade de acertos.

Se eu entendi direito, você quer fazer uma estatística avaliando quais jogos tem 13 acertos? Ou é pelo menos 13 acertos?

**Comment by AdolfoPD** [comment]
É da loteca!

Existem 3^14  (4782969 cartoes)cada cartão tem 28 cartões de 13 pontos!

Quero listar todos os cartões e seus cartões de 13 pontos !

**Comment by AdolfoPD** [comment]
Eu ja tenho em txt os 4782969 cartoes gerados.

Se quiser

**Comment by wagnerluis1982** [comment]
Parece ser interessante, mas infelizmente, no momento, não tenho como ajudar nessa tarefa, a Loteca não está implementada no `sorte.py`.

**Comment by AdolfoPD** [comment]
Blz
